apiVersion: v1
kind: PersistentVolume
metadata:
  name: q3-server-pv
spec:
  storageClassName: retro
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/q3/